version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - mynetwork

  publisher:
    build:
      context: ./publisher
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

  subscriber:
    build:
      context: ./subscriber
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./display-message
    ports:
      - "3000:80"
    networks:
      - mynetwork

networks:
  mynetwork:
